//
//  LocationsDataService.swift
//  TheTahitiSurfBible
//
//  Created by Jerad Acosta on 1/9/23.
//

import MapKit
import Foundation

class LocationsDataService {
    
    static let surfLocations: [SurfLocation] = [
        SurfLocation(name: "Teahupo'o",
                     breakType: "Reef",
                     surferLevel: "Expert",
                     swell: "",
                     tide: "All",
                     crowd: "Crowded on the Weekends",
                     imageNames: ["teahupoo"],
                     about: "A tremendous wave that demands respect, which can only come from experience. Only those who have it, either at this spot or elsewhere, will appreciate what this wave can offer.",
                     localTip: "When at the take off, GO or get out of the line-up",
                     town: "Taiarapu-Ouest",
                     report: "https://magicseaweed.com/Teahupoo-Surf-Report/619/",
                     coordinates: CLLocationCoordinate2D(latitude: -17.8416633, longitude: -149.266998932)),
        SurfLocation(name: "Taharuu",
                     breakType: "Beach",
                     surferLevel: "Beginner",
                     swell: "",
                     tide: "Low",
                     crowd: "Crowded",
                     imageNames: ["taharuu"],
                     about: "The most popular beachbreak on Tahiti and the only good beach break on the West Coast. The waves are not always regular in their shapes but you can have good ones (tubes etc...). It's a great place to learn.",
                     localTip: "A friendly crowd you will often catch local of all levels here and always a few travelers. There is a little bistro right on the beach you can grab a Hinano and sandwich while you watch the waves.",
                     town: "Papara",
                     report: "https://magicseaweed.com/Papara-Surf-Report/3156/",
                     coordinates: CLLocationCoordinate2D(latitude: -17.7711, longitude: -149.4800)),
        SurfLocation(name: "Maraa",
                     breakType: "Reef",
                     surferLevel: "Intermediate to Expert",
                     swell: "West, SouthWest, South",
                     tide: "High",
                     crowd: "Empty",
                     imageNames: ["maraa"],
                     about: "This break is not for the timid or inexperienced. It is a thick, fast wave moving across an extremely shallow reef, even at high tide. The paddle is long and sharky. However it is usually uncrowded and some great sessions can be had with just you and the people you're traveling with.",
                     localTip: "Both the left and right here are more makeable than they appear. Though it is for from an easy wave, once you are in the swing of things you can find yourself taking off closer to the peak for some epic rides.",
                     town: "Paea",
                     report: "",
                     coordinates: CLLocationCoordinate2D(latitude: -17.749995, longitude: -149.581089)),
        SurfLocation(name: "Papenoo",
                     breakType: "Beach",
                     surferLevel: "Beginner",
                     swell: "North, NorthWest, NorthEast",
                     tide: "",
                     crowd: "Crowded",
                     imageNames: ["papenoo"],
                     about: "A very popular beach break that is great for learning how to surf on. The waves are long, mushy, and powerless.",
                     localTip: "This break is swell and crowd friendly to beginners.",
                     town: "Papenoo",
                     report: "https://magicseaweed.com/Papenoo-Surf-Report/820/",
                     coordinates: CLLocationCoordinate2D(latitude: -17.508839, longitude: -149.431336)),
        SurfLocation(name: "Papenoo Rivermouth",
                     breakType: "Beach",
                     surferLevel: "Beginner",
                     swell: "North, NorthWest, NorthEast",
                     tide: "All",
                     crowd: "Crowded, Everyone",
                     imageNames: ["rivermouth"],
                     about: "Along with Paparaa, Papenoo Rivermouth is considered Tahiti's best beach break. The Sandbar is fun and forgiving and is capable of holding up a nice barrel. The outer sandbars break around waist high and will continue comfortably to double overhead. Due to the rivermouth you will find yourself paddling through cold patches of water fairly often.",
                     localTip: "Don't surf here after big rains (sharks and infectious pollution). If no locals are surfing: STAY OUT of the water!",
                     town: "Papenoo",
                     report: "https://magicseaweed.com/Papenoo-Surf-Report/820/",
                     coordinates: CLLocationCoordinate2D(latitude: -17.512645, longitude: -149.418113)),
        SurfLocation(name: "Rocky Point",
                     breakType: "Beach",
                     surferLevel: "Beginner",
                     swell: "North, NorthWest, NorthEast",
                     tide: "All",
                     crowd: "Crowded, Everyone Invited",
                     imageNames: ["rockypoint"],
                     about: "It's a popular spot. There' often something to surf here.",
                     localTip: "Waves here tend to be a bit more fun and longer than PK15. You will most likely pay for it with the added crowd though",
                     town: "Papenoo",
                     report: "https://magicseaweed.com/Papenoo-Surf-Report/820/",
                     coordinates: CLLocationCoordinate2D(latitude: -17.507816, longitude: -149.437623)),
        SurfLocation(name: "Pointe Vénus",
                     breakType: "Reef",
                     surferLevel: "Expert",
                     swell: "NorthEast",
                     tide: "",
                     crowd: "Empty",
                     imageNames: ["pointvenus"],
                     about: "It doesn't break often. The wave is hollow and very fast. The water is shallow.",
                     localTip: "If you have not the required level then stay on the beach!",
                     town: "Mahina",
                     report: "",
                     coordinates: CLLocationCoordinate2D(latitude: -17.495179, longitude: -149.501052)),
        SurfLocation(name: "Col du Tahara'a",
                     breakType: "Reef",
                     surferLevel: "Intermediate",
                     swell: "North, NorthWest, NorthEast",
                     tide: "low tide only",
                     crowd: "Arue",
                     imageNames: ["taharaa"],
                     about: "This wave is a rare gem from the sea of pearls. Rarely breaking but a handful of days each year. It is a short wave in the 50 meter range. The coral reefs sudden appearance gives waves traveling in deep waters a quick ledge to hit, forming a powerful wave in the double overhead size.",
                     localTip: "",
                     town: "",
                     report: "",
                     coordinates: CLLocationCoordinate2D(latitude: -17.515316, longitude: -149.507532)),
        SurfLocation(name: "Papeete Étymologie",
                     breakType: "Reef",
                     surferLevel: "Intermediate",
                     swell: "North, NorthWest, NorthEast",
                     tide: "All",
                     crowd: "Empty",
                     imageNames: ["papeeteetymologie"],
                     about: "One of Tahiti's collection of rare gems this wave can only be caught breaking a couple handful of days a year. It is hollow and fast when it does break, so bring your body board and a pair of fins to enjoy the view from within. The ride is sweet but short in the 50 meter range. The wave breaks at waist high and can hold up to a couple feet over head.",
                     localTip: "If the right is breaking alone: the swell is small and from N to NE and you should go to the North coast. \n If the right and the left are breaking: the swell is big and from NW to NE, take your gun and go to the North coast. \n If only the left is breaking: the swell is big and from W to NW, go to the South West coast (Tapunaa will have difficulty to work).",
                     town: "Papeete",
                     report: "",
                     coordinates: CLLocationCoordinate2D(latitude: -17.534611, longitude: -149.584436)),
        SurfLocation(name: "Vairao",
                     breakType: "Reef",
                     surferLevel: "Intermediate",
                     swell: "SouthWest, South",
                     tide: "All",
                     crowd: "Empty",
                     imageNames: ["vairao"],
                     about: "It's a long paddle. If you aren't in a good shape: find a boat. It's a long, hollow and fun wave. Often bigger than Taapuna. This part of the Island isn't crowded, enjoy it.",
                     localTip: "",
                     town: "Taiarapu-Ouest",
                     report: "",
                     coordinates: CLLocationCoordinate2D(latitude: -17.801405, longitude: -149.31334)),
        SurfLocation(name: "Faaone",
                     breakType: "Beach",
                     surferLevel: "Beginner",
                     swell: "SouthEast, East, NorthEast",
                     tide: "All",
                     crowd: "Empty",
                     imageNames: ["faaone"],
                     about: "It's a uncrowded fun wave. It's sometime the only wave easily accessible which is breaking on the island when the swell is coming from East (not often).",
                     localTip: "",
                     town: "Taiarapu-Est.",
                     report: "",
                     coordinates: CLLocationCoordinate2D(latitude: -17.674774, longitude: -149.305401)),
        SurfLocation(name: "Trou du Souffleur",
                     breakType: "Reef",
                     surferLevel: "Beginner",
                     swell: "North, NorthEast",
                     tide: "All",
                     crowd: "Empty",
                     imageNames: ["troudusouffleur"],
                     about: "This is maybe more of a bodyboard spot than a surf spot but with different conditions it could be a good alternative to the risky reef breaks that scatter themselves all over Tahiti.",
                     localTip: "Park in the Car Park for the Arahoho Blow Hole at Tiarei. The beach and break will be right in front of you!",
                     town: "Taiarapu-Est.",
                     report: "",
                     coordinates: CLLocationCoordinate2D(latitude: -17.524258, longitude: -149.389976)),
        SurfLocation(name: "Orofara",
                     breakType: "Point Break",
                     surferLevel: "Beginner",
                     swell: "North, NorthWest, NorthEast",
                     tide: "All",
                     crowd: "Packed!",
                     imageNames: ["troudusouffleur"],
                     about: "It's a fun right point break. There's always something to surf here. Come here when the NE wind is blowing and the other places are closing out.",
                     localTip: "You can surf this break from waist high to double overhead",
                     town: "Hitiaa O Te Ra",
                     report: "",
                     coordinates: CLLocationCoordinate2D(latitude: -17.524258, longitude: -149.389976))
    ]
}
